<a href="https://colab.research.google.com/github/schizyfos/NLP/blob/master/PrimitiveSentimentAnalysis_SK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
# Creating the trivial sentiment analysis simply from the list of positive and negative words
# To be as quick as possible, I am going to do it in numpy. Therefore I import the numpy library
import numpy as np
import string
import os
# TO PLAY, RUNTIME/RUN ALL

In [99]:
"""
DOWNLOAD FROM KAGGLE NOT SUCCESSFULL, TO BE SKIPPED
!wget --no-check-certificate \
  https://www.kaggle.com/rtatman/sentiment-lexicons-for-81-languages/download/archive.zip \
  -O //content/sample_data/archive.zip
  """

  

'\nDOWNLOAD FROM KAGGLE NOT SUCCESSFULL, TO BE SKIPPED\n!wget --no-check-certificate   https://www.kaggle.com/rtatman/sentiment-lexicons-for-81-languages/download/archive.zip   -O //content/sample_data/archive.zip\n  '

In [100]:
""" WORKED FINE, TO BE SKIPPED
from google.colab import drive
drive.mount('/content/gdrive')
!cp /content/gdrive/MyDrive/archive.zip /content/sample_data/archive.zip
"""


" WORKED FINE, TO BE SKIPPED\nfrom google.colab import drive\ndrive.mount('/content/gdrive')\n!cp /content/gdrive/MyDrive/archive.zip /content/sample_data/archive.zip\n"

In [101]:
""" SUCCESSFULL UNZIP, TO BE SKIPPED
!unzip -q archive.zip
"""

' SUCCESSFULL UNZIP, TO BE SKIPPED\n!unzip -q archive.zip\n'

In [102]:
""" PROVEMENT OF SUCCESS, TO BE SKIPPED
!ls -l
"""

' PROVEMENT OF SUCCESS, TO BE SKIPPED\n!ls -l\n'

In [103]:
# opening the slovak posit/negat words files
# I have set the working directory directly to the lexicon files
os.chdir('/content/sample_data/sentiment-lexicons')
print(os.getcwd())
pozitSlova = open("positive_words_sk.txt", "r")
negatSlova = open("negative_words_sk.txt", "r")
# transforming them into the lists
zozPozit=pozitSlova.read().split('\n')
zozNegat=negatSlova.read().split('\n')

# transforming the lists into numpys
numPozit=np.array(zozPozit)
numNegat=np.array(zozNegat)

#check if all is ok printing the random word indexex and index numbers
print(numPozit)
print(numNegat)
numPozitIndex = np.where(numPozit == 'hravo')
print(numPozitIndex)
numNegatIndex = np.where(numNegat == 'priemerný')
print(numNegatIndex)

/content/sample_data/sentiment-lexicons
['right' 'ako' 'má' ... 'lead' 'hravo' '']
['o' 'položený' 'priemerný' ... 'kontraproduktívne' 'hroziť' '']
(array([1031]),)
(array([2]),)


In [104]:
# Change the working directory
os.chdir('/content/sample_data/sentiment-lexicons/')

In [105]:
# opening the slovak posit/negat words files
pozitSlova = open("positive_words_sk.txt", "r")
negatSlova = open("negative_words_sk.txt", "r")

# transforming them into the lists
zozPozit=pozitSlova.read().split('\n')
zozNegat=negatSlova.read().split('\n')

# transforming the lists into numpys
numPozit=np.array(zozPozit)
numNegat=np.array(zozNegat)

#check if all is ok printing the random word indexes and index numbers
print(numPozit)
print(numNegat)
numPozitIndex = np.where(numPozit == 'hravo')
print(numPozitIndex)
numNegatIndex = np.where(numNegat == 'priemerný')
print(numNegatIndex)

['right' 'ako' 'má' ... 'lead' 'hravo' '']
['o' 'položený' 'priemerný' ... 'kontraproduktívne' 'hroziť' '']
(array([1031]),)
(array([2]),)


In [107]:
#sentence from a user
veta = input("Please enter your sentence and then \ncheck my opinion. If it pops up, scroll all \nthe way \ndown to find my rating : ")

#sentence split to words
slovaVety = veta.split()

#check if all is ok printing the splitted words of a sentence
# print(slovaVety)
i=0
j=0
for item in slovaVety:
# print(item)
  if item in numPozit:
    i += 1
  if item in numNegat:
    j += 1
if i > 0 and j > 0:
    print('inconsistent sentiment')
if i > 0 and j == 0:
    print('positive sentiment')
if i == 0 and j > 0:
    print('negative sentiment')
if i == 0 and j == 0:
    print("I don't know")
# print(i)
# print(j)

Please enter your sentence and then 
check my opinion. If it pops up, scroll all 
the way 
down to find my rating : lepšie ako dobre
positive sentiment
